### ISSUE TITLE
Evidence to support working mothers in companies

### ISSUE THREAD

**Issue by julihcho** [danmek/Gender-Equity-4-Policy#12]

**Comment by julihcho** [comment]
**As** companies that struggle with female employee retention / recruitment, 

**we want** arguments / evidence to expand support working mothers,

**so that** they could take a bigger part in the workforce and participate in the labor force as much as men.

**Comment by julihcho** [comment]
## INVEST

- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

## Tasks
* Identify what kinds of arguments / evidence companies need on female recruitment and retention, specifically for working women (e.g., "highly educated careerwomen still spend disproportionate amounts of time on childcare)
* Identify datasets that will support arguments
* Clean above dataset into a format that can be visualized or analyzed easily
* Sketch out potential visualizations (by hand or excel)
* Develop text content to accompany visualization
* Add image and text on website

## Definition of done
* Show to a company that cares about retention / recruitment of working mothers - ask if they have learned something new or whether this will support management decisions

**Comment by julihcho** [comment]
Note: This was split from a broader user story in the middle of Sprint 1, as we learned about available data.

**Comment by julihcho** [comment]
FYI: https://beta.bls.gov/dataQuery/find?fq=survey:%5Bfm%5D&s=popularity:D

**Comment by kellyyun** [comment]
@julihcho possible data if you're interested in including international maternity/parental/paternity leave visualization: https://www.oecd.org/gender/data/employment/ (second to last link on the page)
