### ISSUE TITLE
Best practices for splitting household activities [8pts]

### ISSUE THREAD

**Issue by julihcho** [danmek/Gender-Equity-4-Policy#4]
**As** a woman balancing my career and household activities, 

**I want** to understand best practices for splitting household activities,

**So that** I can share the burden equally with my partner.

**Comment by danmek** [comment]
## INVEST
- [ ] Independent
- [ ] Negotiable
- [x] Valuable
- [x] Estimable
- [ ] Small
- [x] Testable

## TASKS
- Identify database that can show activities unequally distributed across genders
- Clean data above into a format that can be visualized or analyzed easily
- Identify correlations we want to show between data
- Sketch out potential visualizations (by hand or Excel)
- Identify final visualization to show on website (by hand or Excel)
- Define text content to accompany visualization
- Develop a blank HTML website
- Show visualization on website

## DEFINITION OF DONE

Show to female classmates (who are or intend to be in relationships with men with careers) - have them say "I now know these common traps"

**Comment by danmek** [comment]
**Poker planning insights** [8pts]

MVP: 
- Create an empty HTML website
- visualization will be an image of an Excel sheet
- no styles
- data analysis - might take longer, try to focus on simple data analysis

**Comment by kellyyun** [comment]
Per our team discussion, Dana and Yael will focus on the issue evaluating OECD data for Sprint 1, and we will reevaluate these moved issues in Sprint 2 planning
