### ISSUE TITLE
Common traps men may fall in when splitting chores

### ISSUE THREAD

**Issue by julihcho** [danmek/Gender-Equity-4-Policy#5]
**As** a man who cares about equal partnership, 

**I want** to understand common traps men may fall into when splitting household chores with women,

**So that** I can share the burden equally with my partner

**Comment by danmek** [comment]
Potential task: visualize what activities are unequally distributed between genders in different countries

**Comment by julihcho** [comment]
## INVEST
- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
[Maybe?] Small
- [x] Testable

## TASKS
- Identify database that can show activities unequally distributed across genders
- Clean data above into a format that can be visualized or analyzed easily
- Identify correlations we want to show between data
- Sketch out potential visualizations (by hand or Excel)
- Identify final visualization to show on website (by hand or Excel)
- Define text content to accompany visualization
- Develop a blank HTML website
- Show visualization on website

## DEFINITION OF DONE
- Show to male classmates (who are or intend to be in relationships with women with careers) - have them say "I now know these common traps"

**Comment by danmek** [comment]
*Poker planning insights*
Combine tasks from this story with https://github.com/danmek/Gender-Equity-4-Policy/issues/4

**Comment by kellyyun** [comment]
Per our team discussion, Dana and Yael will focus on the issue evaluating OECD data for Sprint 1, and we will reevaluate these moved issues in Sprint 2 planning
